version: '3.1'
services:
  mysql:
    image: mysql
    container_name: kensu-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: andy
      #MYSQL_USER: andy
      #MYSQL_PASSWORD: andy
    volumes:
      - "./mysql-init-users.sql:/docker-entrypoint-initdb.d/0.sql"
      - "./init-mysql-data.sql:/docker-entrypoint-initdb.d/1.sql"

    ports:
      - 3306:3306

  wildfly:
    image: vidma/wildfly-ksu
    container_name: ksu-wildfly
    restart: unless-stopped
    volumes:
      - ./deployments/sample-service-1.3.0.war:/opt/jboss/wildfly/standalone/deployments/sample-service-1.3.0.war
    ports:
      - 8080:8080
      # ui user: admin password: admin
      - 9990:9990

  clickhouse:
    image: yandex/clickhouse-server 
    container_name: ksu-clickhouse
    volumes:
      - ./01_clickhouse-init.sh:/docker-entrypoint-initdb.d/01_clickhouse-init.sh
      - ./clickhouse-schema.sql:/app/home/clickhouse-schema.sql
      - ./hits_v1.tsv:/app/home/hits_v1.tsv
      - ./visits_v1.tsv:/app/home/visits_v1.tsv
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
